### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by yume-chan** [yume-chan/ya-webadb#348]
## Architecture 

- [x] Rewrite using [Next.js](http://nextjs.org/) framework to improve maintainability
  - [x] Scrcpy
  - [x] Log
  - [x] Install APK
  - [x] File Download
    - [x] Use self-host StreamSaver mitm page jimmywarting/StreamSaver.js#255
  - [x] Improve build size vercel/next.js#25484
- [x] Investigate converting AdbSocket to [DOM Streams](https://streams.spec.whatwg.org/)

## File Manager

- [ ] Multi-select and download as zip
  - [ ] Download as folder using File System API
- [ ] Upload queue
  - [ ] Upload folder

## Scrcpy

- [x] Adapt version 1.18
  - [x] Argument change (powerOffOnClose)
  - [x] Encoder list output format change
  - [x] Back key event format change
- [x] Support multiple server versions
  - [x] 1.16~1.17
  - [x] 1.18~1.20
  - [x] [1.21](https://github.com/Genymobile/scrcpy/releases/tag/v1.21) (major argument format change)
  - [x] 1.22
- [x] Support mouse scroll wheel events
- [x] Support [all mouse buttons](https://github.com/Genymobile/scrcpy#right-click-and-middle-click)

Low Priority:

- [ ] Support macro or keyboard touch mapping Genymobile/scrcpy#712

## Scrcpy decoder

- [x] Use WebCodecs decoder by default
- [ ] Re-investigate possibility of remuxing and MSE decoder ([xevojapan/h264-converter](https://github.com/xevojapan/h264-converter), [ChihChengYang/wfs.js](https://github.com/ChihChengYang/wfs.js), etc)
- [x] Enable H264 High profile for WebCodecs and MSE decoders
- [ ] Use WebCodecs with MSE w3c/media-source#184

## AOA HID emulation

Android Open Accessory: https://source.android.com/devices/accessories/aoa2

- [ ] Keyboard (scrcpy implementation: https://github.com/Genymobile/scrcpy/pull/2632)
- [ ] Mouse (scrcpy implementation: https://github.com/Genymobile/scrcpy/pull/2916)

## Connection

- [ ] Node.js backends
  - [ ] USB (https://github.com/thegecko/webusb)
  - [ ] TCP
- [x] Implement a raw TCP backend using Direct Sockets API #349
  - [ ] `adb pair` mode (Wireless connection without first turning on ADB over WiFi, https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+)

## App management

See #373

## Android binary wrapper

These ADB commands just execute a file on device, and pipe the output

- [ ] logcat/lolcat/longcat - logcat #339 #359
- [ ] backup/restore - /system/bin/bu #354

## Documentation

- [ ] Build and development instruction
- [ ] ADB book

**Comment by yume-chan** [comment]
Will track roadmap using [projects](https://github.com/yume-chan/ya-webadb/projects?type=beta).

**Comment by upintheairsheep** [comment]
Reminder: please finish BU support
